### ISSUE TITLE
Sitecore Version

### ISSUE THREAD

**Issue by goatmale** [thesoftwarejedi/R2Integrated.Sitecore.NewRelicInstrumentation#1]
What Sitecore version(s) does this work for? Trying to add it to my development server yields the error:

Exception Details: System.MissingMethodException: Method not found: 'System.Uri Sitecore.Pipelines.HttpRequest.HttpRequestArgs.get_RequestUrl()'.

[MissingMethodException: Method not found: 'System.Uri Sitecore.Pipelines.HttpRequest.HttpRequestArgs.get_RequestUrl()'.]    R2Integrated.Foundation.NewRelicInstrumentation.NewRelicSetTxNameAndUriPipeline.Process(HttpRequestArgs args) +0    (Object , Object[] ) +167    Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args) +475    Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain) +23    Sitecore.Nexus.Web.HttpModule.(Object , EventArgs ) +490    System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +229    System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +1345
--

**Comment by thesoftwarejedi** [comment]
8.2.5 I believe. I would suggest downloading the code and compiling as part of your solution to identify any possible conflict.
